version: '3'

services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: #volume to consume all zips from
      - /Users/demo/volumes/test/zips:/app/zips
      - /Users/demo/volumes/test/czips:/app/czips
      - /Users/demo/volumes/test/smsc/logs:/var/log # test if logs persist
    environment:
      - TEST=1
    depends_on: # waiting for db up
      - master
      - segment
    networks:
      - backend

  #checker service that ensures all data inserted correctly
  checker:
    build:
      context: .
      dockerfile: checker.Dockerfile
    depends_on:
      - gpfdist
    networks:
      - backend

  gpfdist:
    build: gp/gpfdist
    volumes:
      - /Users/demo/volumes/test/czips:/files/
    command: /usr/lib/gpdb/bin/gpfdist -d /files/ -p 8888
    networks:
        - backend

  #gp for itest
  master:
    build: gp/gpdb/stable
    links:
      - segment
    networks:
      - backend

  segment:
    build: gp/gpdb/stable
    entrypoint: gpdb-seg-entrypoint.sh
    networks:
      - backend




# common network
networks:
  backend: